version: "3.8"
services:
  backend:
    build:
      context: .
    ports: [ 8080:8080 ]
  frontend:
    build:
      context: frontend
    ports: [ 80:8080 ]
  restler:
    build:
      context: restler
    ports: [ 5000:5000 ]
  demo_server:
    build:
      context: demo_server
    ports: [ 8888:8888 ]