version: "3.8"
services:
  backend:
    build:
      context: .
    ports: [ 8080:8080 ]
  frontend:
    build:
      context: frontend
    ports: [ 80:8080 ]
  restler:
    build:
      context: restler
    ports: [ 5000:5000 ]
  demo_server:
    build:
      context: demo_server
    ports: [ 8888:8888 ]
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=ap-southeast-2
      - EDGE_PORT=4566
    #  - SERVICES=lambda,s3,iam,dynamodb,sqs
    #ports: ['4566:4566']
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: host