openapi: 3.0.3
info:
  description: ""
  title: Sample Lambda API
  version: v1.0.0
paths:
  /echo:
    post:
      description: Returns the same string as provided
      operationId: endpoints.PostEcho
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointsPostEchoInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointsPostEchoOutput'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestErrResponse'
          description: Bad Request
      summary: Echo
  /login:
    get:
      description: Return token
      operationId: endpoints.Authentication
      parameters:
      - in: query
        name: code
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointsAuthOutput'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestErrResponse'
          description: Bad Request
      summary: Authentication
  /openapi:
    post:
      description: Recieves the open-api file from client and adds to s3
      operationId: endpoints.Fuzz
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointsCliInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointsCliOutput'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestErrResponse'
          description: Bad Request
      summary: Open Api Fuzz
components:
  schemas:
    EndpointsAuthOutput:
      properties:
        token:
          type: string
      required:
      - token
      type: object
    EndpointsCliInput:
      properties:
        result:
          items:
            minimum: 0
            type: integer
          nullable: true
          type: array
      required:
      - result
      type: object
    EndpointsCliOutput:
      properties:
        result:
          type: string
      required:
      - result
      type: object
    EndpointsPostEchoInput:
      properties:
        request:
          type: string
      required:
      - request
      type: object
    EndpointsPostEchoOutput:
      properties:
        result:
          type: string
      required:
      - result
      type: object
    RestErrResponse:
      properties:
        code:
          description: Application-specific error code.
          type: integer
        context:
          additionalProperties: {}
          description: Application context.
          type: object
        error:
          description: Error message.
          type: string
        status:
          description: Status text.
          type: string
      required:
      - code
      - context
      - error
      - status
      type: object
