openapi: 3.0.3
info:
  description: ""
  title: Sample Lambda API
  version: v1.0.0
paths:
  /echo:
    post:
      description: Returns the same string as provided
      operationId: endpoints.PostEcho
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointsPostEchoInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointsPostEchoOutput'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestErrResponse'
          description: Bad Request
      summary: Echo
  /login:
    post:
<<<<<<< HEAD
      description: Get token from GitHub
      operationId: cmd/endpoints.Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointsAuthInput'
=======
      description: Return code
      operationId: endpoints.Authentication
      parameters:
      - in: query
        name: code
        schema:
          type: string
>>>>>>> main
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointsAuthOutput'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestErrResponse'
          description: Bad Request
<<<<<<< HEAD
      summary: Login
components:
  schemas:
     EndpointsAuthInput:
      properties:
        code:
          type: string
      required:
      - request
      type: object
     EndpointsAuthOutput:
=======
      summary: code
components:
  schemas:
    EndpointsAuthOutput:
>>>>>>> main
      properties:
        token:
          type: string
      required:
<<<<<<< HEAD
      - request
=======
      - token
      type: object
>>>>>>> main
    EndpointsPostEchoInput:
      properties:
        request:
          type: string
      required:
      - request
      type: object
    EndpointsPostEchoOutput:
      properties:
        result:
          type: string
      required:
      - result
      type: object
    RestErrResponse:
      properties:
        code:
          description: Application-specific error code.
          type: integer
        context:
          additionalProperties: {}
          description: Application context.
          type: object
        error:
          description: Error message.
          type: string
        status:
          description: Status text.
          type: string
      required:
      - code
      - context
      - error
      - status
      type: object
